##########################################################################
#                                                                        #
#                          App Identity Part                         #
#               For Further information, please check README             #
#                                                                        #
##########################################################################

app:
  name: "maskan"
  baseURL: "/v1"
  http:
    host: "localhost"
    port: "8080"
    cors: ""
##########################################################################
#                                                                        #
#                         Server Config Part                             #
#       Please set the server parameters based on your own settings      #
#                                                                        #
##########################################################################

jaeger:
  hostPort: "jaeger:6831"
  logSpans: true

redis:
  username: ""
  password: ""
  db: 0
  host: "redis:6379"
  logger: ""

etcd:
  username: "ruserasdasdasd"
  password: "T0pS3cr3t"
  watchlist:
  endpoints:
    - http://etcd0:2379

postgres:
  username: "admin"
  password: "password"
  host: "postgres:5432"
  schema: "maskan"

Nats:
  username: ""
  password: ""
  encoder: "json"
  auth: false
  allowReconnect: true
  maxReconnect: 50
  reconnectWait: 5
  timeout: 3
  endpoints:
    - "nats://nats:4222"

jwt:
  hmacSecret: "xxxxxxxxxxxxx"

logstash:
  endpoint: "logstash:5000"
  timeout: 5 # second
