FROM golang:1.19

RUN mkdir -p /build

WORKDIR /build

ADD . .

RUN mkdir -p /temp
# RUN go get ./... && go mod vendor && go mod verify

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

CMD ["./run.sh"]