name: Integration tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  intergraion-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: e35YtGPSz6agLyJH
          POSTGRES_USER: nftadmin
          POSTGRES_DB: nft
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - run: go mod tidy
      - run: make config
      - run: mkdir ./test/temp
      - run: go install github.com/swaggo/swag/cmd/swag@latest
      - run: swag fmt
      - run: swag init
      - run: go test ./test/...
